# ---------------------------------------------------------------------------
# CI workflows for MTDA
# ---------------------------------------------------------------------------
#
# This software is a part of MTDA.
# Copyright (C) 2024 Siemens Digital Industries Software
#
# ---------------------------------------------------------------------------
# SPDX-License-Identifier: MIT
# ---------------------------------------------------------------------------

name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    types: [ labeled ]

jobs:
  lint:
    name: Check code for issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: tox
        run: |
          sudo apt install -y build-essential libsystemd-dev
          pip3 install --user tox
          tox -s
  mtda-yocto-build:
    name: Yocto image build for MTDA on poky qemu arm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build image
        if: github.ref == 'refs/heads/master'
        run: |
          export KAS_BUILD_DIR=${PWD}/build-yocto
          ./kas-container build kas/yocto/mtda-qemu-yocto.yml
