# ---------------------------------------------------------------------------
# CI workflows for MTDA
# ---------------------------------------------------------------------------
#
# This software is a part of MTDA.
# Copyright (C) 2024 Siemens Digital Industries Software
#
# ---------------------------------------------------------------------------
# SPDX-License-Identifier: MIT
# ---------------------------------------------------------------------------

name: CI

on:
  push:
    branches:
      - yocto-ci-test
    tags:
      - v*
  pull_request:
    types: [ labeled ]

jobs:
  lint:
    name: Check code for issues
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: tox
        run: |
          sudo apt install -y build-essential libsystemd-dev
          pip3 install --user tox
          tox -s
  mtda-yocto-build:
    name: mtda yocto package build for poky qemu arm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: |
          export KAS_BUILD_DIR=${PWD}/build-yocto
          ./kas-container build --target mtda kas/yocto/mtda-qemu-yocto.yml
  mtda-image-yocto-build:
    name: Yocto image build for MTDA on poky qemu arm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: |
          export KAS_BUILD_DIR=${PWD}/build-yocto
          ./kas-container build kas/yocto/mtda-qemu-yocto.yml
